language: objective-c
osx_image: xcode8.3
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "dyld_cache_extract.xcodeproj" -scheme "dyld_cache_extract" build analyze | xcpretty
- set -o pipefail && xcodebuild -project "dyld_cache_extract.xcodeproj" -scheme "DCE-GUI" build analyze | xcpretty
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
